### ISSUE TITLE
go版本的client客户端如何使用vnstat？

### ISSUE THREAD

**Issue by Terry-Lzz** [cokemine/nodestatus-client-go#12]
go版本的client客户端如何使用vnstat？
看了下代码，是不是client.go的main函数里漏写了对vnstat参数的判断？

**Comment by cokemine** [comment]
运行时加入 -vnstat 即可

可以把服务的运行命令改成
`ExecStart=/usr/local/NodeStatus/client/status-client --dsn $DSN -vnstat`
