### ISSUE TITLE
macOS 运行出错

### ISSUE THREAD

**Issue by Clansty** [cokemine/nodestatus-client-go#18]
运行命令：

```bash
status-client --dsn wss://xxx:xxx@xxx.xxx.xxx
```

加不加 sudo 都一样

报错信息：

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cokemine/ServerStatus-goclient/pkg/status.Cpu(0xc0000163d8, 0xc00039cd90)
	/home/runner/go/pkg/mod/github.com/cokemine/!server!status-goclient@v1.1.10/pkg/status/status.go:77 +0x130
main.connect()
	/home/runner/work/nodestatus-client-go/nodestatus-client-go/cmd/client/client.go:104 +0x476
main.main()
	/home/runner/work/nodestatus-client-go/nodestatus-client-go/cmd/client/client.go:182 +0x1a5
```

**Comment by cokemine** [comment]
https://github.com/cokemine/ServerStatus-goclient/issues/10
cpu.Percent() darwin 下需要开启 cgo 才能用，我再看看 GitHub Action 能不能交叉编译

**Comment by Clansty** [comment]
> 我再看看 GitHub Action 能不能交叉编译

GitHub 有 macOS 的 runner

**Comment by cokemine** [comment]
> > 我再看看 GitHub Action 能不能交叉编译
> 
> GitHub 有 macOS 的 runner

GitHub mac 的 runner 只能跑 x86_64，ARM 还是需要交叉编译。
我看 Goreleaser 提供了一个官方的方案，本地跑了跑可以编译，需要待会修改下 Action（

**Comment by cokemine** [comment]
试试最新的这个 Release https://github.com/cokemine/nodestatus-client-go/releases/tag/v1.0.6
cc @Clansty

**Comment by Clansty** [comment]
看起来能用，并且负载和内存信息是正常的（NodeJS 版不正常）。但是硬盘和交换空间信息无法读取（NodeJS 版可以读取）

以及 硬盘信息在使用像 btrfs，apfs 这种有子卷功能的文件系统并且挂载了多个子卷的时候，同一个分区的容量会被计算多次。这导致可能可用空间的百分比比较正常，但是容量显示不正常

**Comment by cokemine** [comment]
Try https://github.com/cokemine/nodestatus-client-go/releases/tag/v1.0.7

**Comment by Clansty** [comment]
它可以了！
