### ISSUE TITLE
今天早上服务器自动重启后就有部分掉线了，看了一下不明白问题出在哪里

### ISSUE THREAD

**Issue by lion-goose** [cokemine/nodestatus-client-go#3]
![捕获](https://user-images.githubusercontent.com/59443350/135954918-4270a5f7-0575-481f-83a7-da8def9c3806.JPG)
![捕获1](https://user-images.githubusercontent.com/59443350/135954922-2ae3cc07-cebe-4e4a-bd7e-e282d007948c.JPG)
这两个是掉线的status
![捕获2](https://user-images.githubusercontent.com/59443350/135954955-e25a1eaa-a106-4f65-bfb9-12d2f2a21ce3.JPG)
这个是正常的在线的status

是不是域名解析出现了错误，找不到服务器。
而且在两台掉线的机器上直接ping域名，发现ping不通，为什么会突然这样呢？

**Comment by lion-goose** [comment]
稀里糊涂的解决了，我编辑了/etc/hosts，添加了域名和主机ip映射，就又在线了....

**Comment by cokemine** [comment]
应该是域名 DNS 的问题

**Comment by lion-goose** [comment]
> 应该是域名 DNS 的问题

就是突然出现这样的状况，不知道什么原因，AZ的机器可以设置DNS，Oracle还没有找到在哪里设置……
