### ISSUE TITLE
一键脚本问题咨询

### ISSUE THREAD

**Issue by szsyzx** [cokemine/nodestatus-client-go#9]
假设你的服务端地址是https://tz.mydomain.com，客户端用户名username，密码password

服务端地址如果没有使用反代 是不是要加上端口号啊

DSN="wss://username:password@tz.mydomain.com:端口号

还是必须反代以后才可以用啊

**Comment by cokemine** [comment]
如果你不需要反代的话，访问 Web 界面和客户端连接时都需要加上端口号。
如果你反代并使用了 HTTPS，那客户端连接时就要用 wss
如果没有反代或反代没有用 HTTPS，那客户端连接要用 ws

**Comment by szsyzx** [comment]
懂了，老大不用宝塔有木有其他方便的反代方式啊

**Comment by cokemine** [comment]
我更推荐之间安装 Nginx 进行反代。反代实例在主仓库的文档里有。
如果用的是 Debian 11 那么仓库源足够新可以直接从 Debian 源安装。低版本系统可能需要手动添加 Nginx 的源安装
```
apt install nginx
```

**Comment by szsyzx** [comment]
对菜鸟的我来说太难了啊，安装完nginx是不是还得申请ssl啊
